"""add oms config tables

Revision ID: c45e734bb80b
Revises: 75614e13273d
Create Date: 2026-01-07 22:33:06.038737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45e734bb80b'
down_revision = '75614e13273d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('db_tier', sa.String(length=64), nullable=False),
    sa.Column('rank_level', sa.Integer(), nullable=False),
    sa.Column('requires_rnaseq', sa.Boolean(), nullable=False),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('fasta_location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_requests_job_id'), ['job_id'], unique=False)

    op.create_table('job_raw_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('location_uri', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_raw_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_raw_files_job_id'), ['job_id'], unique=False)

    op.create_table('microproteome_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(length=32), nullable=False),
    sa.Column('min_len', sa.Integer(), nullable=False),
    sa.Column('max_len', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('microproteome_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_microproteome_rounds_job_id'), ['job_id'], unique=False)

    op.create_table('search_configs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=64), nullable=False),
    sa.Column('species', sa.String(length=128), nullable=False),
    sa.Column('instrument', sa.String(length=128), nullable=True),
    sa.Column('ms_mode', sa.String(length=16), nullable=False),
    sa.Column('tmt_label_type', sa.String(length=32), nullable=False),
    sa.Column('tmt_plex', sa.Integer(), nullable=True),
    sa.Column('tmt_labelling_schema', sa.Text(), nullable=True),
    sa.Column('carbamidomethylated', sa.Boolean(), nullable=False),
    sa.Column('additional_mods', sa.JSON(), nullable=True),
    sa.Column('sample_description', sa.Text(), nullable=True),
    sa.Column('search_engines_mode', sa.String(length=64), nullable=False),
    sa.Column('additional_searches', sa.JSON(), nullable=True),
    sa.Column('hla_typing_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('validation_configs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hla_binding', sa.Boolean(), nullable=False),
    sa.Column('conflict_resolution_delta_score_filter', sa.Boolean(), nullable=False),
    sa.Column('pep_filter', sa.Boolean(), nullable=False),
    sa.Column('two_search_engine_agreement', sa.Boolean(), nullable=False),
    sa.Column('pd_infrys_validation', sa.Boolean(), nullable=False),
    sa.Column('pepquery', sa.Boolean(), nullable=False),
    sa.Column('rnaseq_mapping_read_quant', sa.Boolean(), nullable=False),
    sa.Column('genome_mapping_tool', sa.String(length=64), nullable=True),
    sa.Column('immunogenicity_analysis', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_configs')
    op.drop_table('search_configs')
    with op.batch_alter_table('microproteome_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_microproteome_rounds_job_id'))

    op.drop_table('microproteome_rounds')
    with op.batch_alter_table('job_raw_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_raw_files_job_id'))

    op.drop_table('job_raw_files')
    with op.batch_alter_table('database_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_requests_job_id'))

    op.drop_table('database_requests')
    # ### end Alembic commands ###
